version: '2.1'
services:

    mailpipe:
        build: .
        image: mailpipe
        volumes:
            - ./:/code
            - ./mailpipe_home:/root/
        hostname: mailpipe
        environment:
            - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-mailpipe_project.settings}
            - DJANGO_DEBUG=${DJANGO_DEBUG:-false}
        ports:
            - "${MAILPIPE_HTTP_PORT:-8000}:8000"
        command: "start_mailpipe"


    mailserver:
        build: .
        image: mailpipe
        environment:
            - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-mailpipe_project.settings}
            - DJANGO_DEBUG=${DJANGO_DEBUG:-false}
        volumes:
            - ./:/code
            - /code/mailserver/run/
        hostname: mailserver
        ports:
            - "${MAILPIPE_SMTP_PORT:-25}:8025"
        command: "start_mailserver"


